version: '3'

services:
    stt:
        image: stt
        build: .
        ports: 
            - "8000"
        volumes: 
            - static:/app/static
            - /home/waser/.assistant/models/fr/SR/:/share/STT/models/
        networks:
            - frontend
    
    nginx:
        image: nginx:latest
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - static:/mnt/www/data/static
        networks:
            - frontend
        depends_on:
            - stt

networks:
    frontend:
        driver: bridge

volumes:
    static: